# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.4"

volumes:
    orderer.iiitm.com:
    peer0.examiners.iiitm.com:
    peer1.examiners.iiitm.com:
    peer2.examiners.iiitm.com:
    peer3.examiners.iiitm.com:
    peer0.students.iiitm.com:
    peer1.students.iiitm.com:
    peer2.students.iiitm.com:
    peer3.students.iiitm.com:

networks:
    test:
        name: fabric_test

services:
    orderer.iiitm.com:
        container_name: orderer.iiitm.com
        image: hyperledger/fabric-orderer:latest
        labels:
            service: hyperledger-fabric
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
            # enabled TLS
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
            - ORDERER_CHANNELPARTICIPATION_ENABLED=true
            - ORDERER_ADMIN_TLS_ENABLED=true
            - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
            - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
            - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
            - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
            - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ../organizations/ordererOrganizations/iiitm.com/orderers/orderer.iiitm.com/msp:/var/hyperledger/orderer/msp
            - ../organizations/ordererOrganizations/iiitm.com/orderers/orderer.iiitm.com/tls/:/var/hyperledger/orderer/tls
            - orderer.iiitm.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050
            - 7053:7053
        networks:
            - test

    peer0.examiners.iiitm.com:
        container_name: peer0.examiners.iiitm.com
        image: hyperledger/fabric-peer:latest
        labels:
            service: hyperledger-fabric
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer0.examiners.iiitm.com
            - CORE_PEER_ADDRESS=peer0.examiners.iiitm.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.examiners.iiitm.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.examiners.iiitm.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.examiners.iiitm.com:7051
            - CORE_PEER_LOCALMSPID=ExaminersMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer0.examiners.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer0.examiners.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer0.examiners.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 7051:7051
        networks:
            - test

    peer1.examiners.iiitm.com:
        container_name: peer1.examiners.iiitm.com
        image: hyperledger/fabric-peer:latest
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            # the following setting starts chaincode containers on the same
            # bridge network as the peers
            # https://docs.docker.com/compose/networking/
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer1.examiners.iiitm.com
            - CORE_PEER_ADDRESS=peer1.examiners.iiitm.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer1.examiners.iiitm.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.examiners.iiitm.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.examiners.iiitm.com:8051
            - CORE_PEER_LOCALMSPID=ExaminersMSP
        volumes:
            - /var/run/:/host/var/run/
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer1.examiners.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer1.examiners.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer1.examiners.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 8051:8051
        networks:
            - test

    peer2.examiners.iiitm.com:
        container_name: peer2.examiners.iiitm.com
        image: hyperledger/fabric-peer:latest
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            # the following setting starts chaincode containers on the same
            # bridge network as the peers
            # https://docs.docker.com/compose/networking/
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer2.examiners.iiitm.com
            - CORE_PEER_ADDRESS=peer2.examiners.iiitm.com:10051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_CHAINCODEADDRESS=peer2.examiners.iiitm.com:10052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.examiners.iiitm.com:10051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.examiners.iiitm.com:10051
            - CORE_PEER_LOCALMSPID=ExaminersMSP
        volumes:
            - /var/run/:/host/var/run/
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer2.examiners.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer2.examiners.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer2.examiners.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 10051:10051
        networks:
            - test
    
    peer3.examiners.iiitm.com:
        container_name: peer3.examiners.iiitm.com
        image: hyperledger/fabric-peer:latest
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            # the following setting starts chaincode containers on the same
            # bridge network as the peers
            # https://docs.docker.com/compose/networking/
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer3.examiners.iiitm.com
            - CORE_PEER_ADDRESS=peer3.examiners.iiitm.com:11051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
            - CORE_PEER_CHAINCODEADDRESS=peer3.examiners.iiitm.com:11052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.examiners.iiitm.com:11051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.examiners.iiitm.com:11051
            - CORE_PEER_LOCALMSPID=ExaminersMSP
        volumes:
            - /var/run/:/host/var/run/
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer3.examiners.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/examiners.iiitm.com/peers/peer3.examiners.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer3.examiners.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 11051:11051
        networks:
            - test

    peer0.students.iiitm.com:
        container_name: peer0.students.iiitm.com
        image: hyperledger/fabric-peer:latest
        labels:
            service: hyperledger-fabric
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer0.students.iiitm.com
            - CORE_PEER_ADDRESS=peer0.students.iiitm.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.students.iiitm.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.students.iiitm.com:9051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.students.iiitm.com:9051
            - CORE_PEER_LOCALMSPID=StudentsMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer0.students.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer0.students.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer0.students.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 9051:9051
        networks:
            - test
    
    peer1.students.iiitm.com:
        container_name: peer1.students.iiitm.com
        image: hyperledger/fabric-peer:latest
        labels:
            service: hyperledger-fabric
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer1.students.iiitm.com
            - CORE_PEER_ADDRESS=peer1.students.iiitm.com:12051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
            - CORE_PEER_CHAINCODEADDRESS=peer1.students.iiitm.com:12052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.students.iiitm.com:12051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.students.iiitm.com:12051
            - CORE_PEER_LOCALMSPID=StudentsMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer1.students.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer1.students.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer1.students.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 12051:12051
        networks:
            - test

    peer2.students.iiitm.com:
        container_name: peer2.students.iiitm.com
        image: hyperledger/fabric-peer:latest
        labels:
            service: hyperledger-fabric
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer2.students.iiitm.com
            - CORE_PEER_ADDRESS=peer2.students.iiitm.com:13051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
            - CORE_PEER_CHAINCODEADDRESS=peer2.students.iiitm.com:13052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.students.iiitm.com:13051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.students.iiitm.com:13051
            - CORE_PEER_LOCALMSPID=StudentsMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer2.students.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer2.students.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer2.students.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 13051:13051
        networks:
            - test
    
    peer3.students.iiitm.com:
        container_name: peer3.students.iiitm.com
        image: hyperledger/fabric-peer:latest
        labels:
            service: hyperledger-fabric
        environment:
            #Generic peer variables
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_PROFILE_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
            # Peer specific variabes
            - CORE_PEER_ID=peer3.students.iiitm.com
            - CORE_PEER_ADDRESS=peer3.students.iiitm.com:14051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
            - CORE_PEER_CHAINCODEADDRESS=peer3.students.iiitm.com:14052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.students.iiitm.com:14051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.students.iiitm.com:14051
            - CORE_PEER_LOCALMSPID=StudentsMSP
        volumes:
            - /var/run/docker.sock:/host/var/run/docker.sock
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer3.students.iiitm.com/msp:/etc/hyperledger/fabric/msp
            - ../organizations/peerOrganizations/students.iiitm.com/peers/peer3.students.iiitm.com/tls:/etc/hyperledger/fabric/tls
            - peer3.students.iiitm.com:/var/hyperledger/production
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        ports:
            - 14051:14051
        networks:
            - test

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:latest
        labels:
            service: hyperledger-fabric
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            #- FABRIC_LOGGING_SPEC=DEBUG
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
            - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        depends_on:
            - peer0.examiners.iiitm.com
            - peer1.examiners.iiitm.com
            - peer2.examiners.iiitm.com
            - peer3.examiners.iiitm.com
            - peer0.students.iiitm.com
            - peer1.students.iiitm.com
            - peer2.students.iiitm.com
            - peer3.students.iiitm.com
        networks:
            - test
